# Generated by Django 6.0.4 on 2026-04-20 03:59

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('polls', '0005_remove_horarios_anio_remove_horarios_dia'),
    ]

    operations = [
        migrations.CreateModel(
            name='PeriodoNomina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_periodo', models.CharField(choices=[('SEMANAL', 'Semanal'), ('QUINCENAL', 'Quincenal'), ('MENSUAL', 'Mensual')], default='QUINCENAL', max_length=20)),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField()),
                ('descripcion', models.CharField(blank=True, max_length=100, null=True)),
                ('cerrado', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['-fecha_inicio'],
            },
        ),
        migrations.CreateModel(
            name='ReciboPago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_emision', models.DateField(default=django.utils.timezone.now)),
                ('salario_base', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('total_percepciones', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('total_deducciones', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('neto_pagar', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('notas', models.TextField(blank=True, null=True)),
                ('periodo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recibos', to='nomina.periodonomina')),
                ('trabajador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recibos', to='polls.trabajador')),
            ],
            options={
                'unique_together': {('trabajador', 'periodo')},
            },
        ),
        migrations.CreateModel(
            name='Percepcion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('SALARIO_BASE', 'Salario Base'), ('BONO', 'Bono'), ('HORAS_EXTRA', 'Horas Extra'), ('VACACIONES', 'Vacaciones'), ('OTROS', 'Otros')], default='SALARIO_BASE', max_length=20)),
                ('descripcion', models.CharField(max_length=100)),
                ('monto', models.DecimalField(decimal_places=2, max_digits=10)),
                ('recibo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='percepciones', to='nomina.recibopago')),
            ],
        ),
        migrations.CreateModel(
            name='Deduccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('ISR', 'ISR'), ('IMSS', 'IMSS'), ('INFONAVIT', 'INFONAVIT'), ('PRESTAMO', 'Préstamo'), ('OTROS', 'Otros')], default='ISR', max_length=20)),
                ('descripcion', models.CharField(max_length=100)),
                ('monto', models.DecimalField(decimal_places=2, max_digits=10)),
                ('recibo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deducciones', to='nomina.recibopago')),
            ],
        ),
    ]
