# Generated by Django 6.0.4 on 2026-04-20 04:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nomina', '0001_initial'),
        ('polls', '0005_remove_horarios_anio_remove_horarios_dia'),
    ]

    operations = [
        migrations.CreateModel(
            name='SalarioBase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('salario_diario', models.DecimalField(decimal_places=2, help_text='Salario diario del trabajador', max_digits=10)),
                ('salario_mensual', models.DecimalField(blank=True, decimal_places=2, help_text='Salario mensual (calculado)', max_digits=10, null=True)),
                ('activo', models.BooleanField(default=True)),
                ('trabajador', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='salario_base', to='polls.trabajador')),
            ],
        ),
    ]
