# Generated by Django 6.0.4 on 2026-04-20 04:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nomina', '0002_salariobase'),
    ]

    operations = [
        migrations.AddField(
            model_name='recibopago',
            name='dias_trabajados',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Días efectivamente trabajados', max_digits=5),
        ),
        migrations.AddField(
            model_name='recibopago',
            name='horas_extras',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Horas extras trabajadas', max_digits=5),
        ),
        migrations.AddField(
            model_name='recibopago',
            name='retardos',
            field=models.IntegerField(default=0, help_text='Número de retardos'),
        ),
    ]
