# Generated by Django 6.0.4 on 2026-04-20 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nomina', '0003_add_recibo_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='recibopago',
            name='horario_turno',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='recibopago',
            name='horas_por_turno',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AddField(
            model_name='recibopago',
            name='lugar_servicio',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='recibopago',
            name='puesto',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='deduccion',
            name='tipo',
            field=models.CharField(choices=[('PRESTAMO', 'Préstamo'), ('FALTAS', 'Faltas'), ('OTROS', 'Otros')], default='PRESTAMO', max_length=20),
        ),
        migrations.AlterField(
            model_name='percepcion',
            name='tipo',
            field=models.CharField(choices=[('BONO', 'Bono'), ('HORAS_EXTRA', 'Horas Extra'), ('VACACIONES', 'Vacaciones'), ('OTROS', 'Otros')], default='BONO', max_length=20),
        ),
    ]
