# Generated by Django 5.2.6 on 2025-10-01 18:20

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Trabajador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=128)),
                ('apellido', models.CharField(blank=True, max_length=128, null=True)),
                ('fecha_ingreso', models.DateTimeField(default=django.utils.timezone.now)),
                ('estado', models.CharField(blank=True, default='Activo', max_length=64, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Servicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_lugar', models.CharField(max_length=128)),
                ('fecha_inicio', models.DateTimeField(default=django.utils.timezone.now)),
                ('fecha_fin', models.DateTimeField(blank=True, null=True)),
                ('direccion', models.CharField(max_length=128)),
                ('trabajador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='servicios', to='polls.trabajador')),
            ],
        ),
        migrations.CreateModel(
            name='Horarios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hora', models.CharField(max_length=128)),
                ('dia', models.CharField(max_length=128)),
                ('mes', models.CharField(max_length=128)),
                ('anio', models.CharField(max_length=128)),
                ('trabajador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='horarios', to='polls.trabajador')),
            ],
        ),
        migrations.CreateModel(
            name='Documentos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cuip', models.CharField(max_length=128)),
                ('antecedentes', models.CharField(max_length=128)),
                ('situacion_fiscal', models.CharField(max_length=128)),
                ('curp', models.CharField(max_length=128)),
                ('nss', models.CharField(max_length=128)),
                ('cursos', models.CharField(max_length=128)),
                ('certificado_estudios', models.CharField(max_length=128)),
                ('trabajador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documentos', to='polls.trabajador')),
            ],
        ),
    ]
