# Generated by Django 5.2.6 on 2025-11-14 18:34

import polls.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentos',
            name='antecedentes',
            field=models.FileField(blank=True, null=True, upload_to=polls.models.documentos_path),
        ),
        migrations.AlterField(
            model_name='documentos',
            name='certificado_estudios',
            field=models.FileField(blank=True, null=True, upload_to=polls.models.documentos_path),
        ),
        migrations.AlterField(
            model_name='documentos',
            name='cuip',
            field=models.FileField(blank=True, null=True, upload_to=polls.models.documentos_path),
        ),
        migrations.AlterField(
            model_name='documentos',
            name='curp',
            field=models.FileField(blank=True, null=True, upload_to=polls.models.documentos_path),
        ),
        migrations.AlterField(
            model_name='documentos',
            name='cursos',
            field=models.FileField(blank=True, null=True, upload_to=polls.models.documentos_path),
        ),
        migrations.AlterField(
            model_name='documentos',
            name='nss',
            field=models.FileField(blank=True, null=True, upload_to=polls.models.documentos_path),
        ),
        migrations.AlterField(
            model_name='documentos',
            name='situacion_fiscal',
            field=models.FileField(blank=True, null=True, upload_to=polls.models.documentos_path),
        ),
    ]
