# Generated by Django 5.2.6 on 2025-12-18 19:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_trabajador_apellido_materno_trabajador_calle_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='horarios',
            name='hora_entrada',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='horarios',
            name='hora_salida',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='horarios',
            name='nombre_turno',
            field=models.CharField(blank=True, choices=[('MATUTINO', 'Matutino'), ('VESPERTINO', 'Vespertino'), ('NOCTURNO', 'Nocturno')], max_length=20, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='horarios',
            unique_together={('nombre_turno',)},
        ),
        migrations.AlterModelOptions(
            name='horarios',
            options={'ordering': ['nombre_turno']},
        ),
        migrations.AlterField(
            model_name='trabajador',
            name='horario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='trabajadores', to='polls.horarios'),
        ),
        migrations.RemoveField(
            model_name='horarios',
            name='hora',
        ),
        migrations.RemoveField(
            model_name='horarios',
            name='mes',
        ),
        migrations.RemoveField(
            model_name='horarios',
            name='trabajador',
        ),
    ]
