# Generated by Django 6.0.4 on 2026-04-20 03:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0004_alter_horarios_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='horarios',
            name='anio',
        ),
        migrations.RemoveField(
            model_name='horarios',
            name='dia',
        ),
    ]
